export const company = {
  name: "Sukaj SHPK",
  established: 1995,
  capital: "74,482,766 ALL",
  location: "Shkodër, Albania",
  administrator: "Musli Sukaj",
  activity: "Import-export of plastic materials & wholesale trading",
  tagline: "Industrial plastic pipe systems — imported and distributed across the Balkans since 1995.",
  description:
    "Founded in 1995, Sukaj SHPK is an import-export and wholesale trading company headquartered in the Shkodër area. We supply complete pipe-system solutions for civil drainage, agricultural irrigation, and industrial routing projects, combining European manufacturing partnerships with regional logistics expertise.",
  stats: {
    yearsExperience: 30,
    countriesServed: 12,
    projectsCompleted: 2500,
    partnersCount: 17,
  },
};

export type PartnerType =
  | "manufacturer"
  | "recycler"
  | "packaging"
  | "hoses"
  | "local-albania";

export interface Partner {
  id: string;
  name: string;
  country: string;
  specialty: string;
  tagline: string;
  maxDiameter?: string;
  factorySize?: string;
  description: string;
  website: string;
  partnerType: PartnerType;
  keyStandards: string[];
  heroMetrics: string[];
  logo: { light?: string; dark?: string };
  featuredPriority: number;
  products: { name: string; type: string; diameters: string }[];
  featured: boolean;
  color: string;
}

export const partners: Partner[] = [
  {
    id: "konti-hidroplast",
    name: "Konti Hidroplast",
    country: "North Macedonia",
    specialty: "PE/PP Pipe Producer — Spiral & Solid Wall",
    tagline: "Export-oriented pipe manufacturing since 1975",
    maxDiameter: "Ø 2000 mm",
    description:
      "Founded in 1975, Konti Hidroplast is one of the region's largest PE/PP pipe producers. Their spiral-wound sewage pipes reach diameters up to 2000 mm, serving export markets across Southeast Europe.",
    website: "https://konti-hidroplast.com.mk",
    partnerType: "manufacturer",
    keyStandards: ["EN 13476", "EN 12201"],
    heroMetrics: ["Ø up to 2000 mm", "95 % export", "Est. 1975"],
    logo: { dark: "/partners/konti-hidroplast/logo.svg", light: "/partners/konti-hidroplast/logo-light.svg" },
    featuredPriority: 1,
    products: [
      { name: "Spiral Sewage Pipe", type: "PP Spiral", diameters: "300–2000 mm" },
      { name: "Solid Wall PE Pipe", type: "PE100", diameters: "20–630 mm" },
    ],
    featured: true,
    color: "#0891b2",
  },
  {
    id: "ferplast-ks",
    name: "Ferplast",
    country: "Kosovo",
    specialty: "Corrugated HDPE Pipes SN4/SN8",
    tagline: "Corrugated pipe specialist since 1996",
    maxDiameter: "ID 2000 mm",
    description:
      "Founded in 1996, Ferplast produces corrugated HDPE pipes in SN4 and SN8 stiffness classes with outer/inner diameter ranges up to ID 2000, plus additional pipe categories for infrastructure.",
    website: "https://ferplast-ks.com",
    partnerType: "manufacturer",
    keyStandards: ["EN 13476", "SN4", "SN8"],
    heroMetrics: ["ID up to 2000 mm", "SN4 / SN8", "Est. 1996"],
    logo: { dark: "/partners/ferplast-ks/logo.svg", light: "/partners/ferplast-ks/logo-light.svg" },
    featuredPriority: 2,
    products: [
      { name: "Corrugated HDPE SN4", type: "HDPE Corrugated", diameters: "100–2000 mm" },
      { name: "Corrugated HDPE SN8", type: "HDPE Corrugated", diameters: "100–1200 mm" },
    ],
    featured: true,
    color: "#a855f7",
  },
  {
    id: "teqja",
    name: "Teqja International",
    country: "Albania",
    specialty: "HDPE 100 & Corrugated Pipe Manufacturer",
    tagline: "Albanian manufacturer with ISO certification",
    maxDiameter: "Ø 630 mm",
    description:
      "Teqja International manufactures HDPE 100 pipes from 20–630 mm (PN4–PN32) and corrugated pipes per EN 13476-1:2018 in 12 m lengths. ISO-certified production for water and sewage networks.",
    website: "https://teqja.com.al",
    partnerType: "local-albania",
    keyStandards: ["EN 13476-1:2018", "ISO 9001", "HDPE PE100"],
    heroMetrics: ["Ø 20–630 mm", "PN4–PN32", "12 m lengths"],
    logo: { dark: "/partners/teqja/logo.svg", light: "/partners/teqja/logo-light.svg" },
    featuredPriority: 3,
    products: [
      { name: "HDPE 100 Pressure Pipe", type: "HDPE PE100", diameters: "20–630 mm" },
      { name: "Corrugated Sewage Pipe", type: "HDPE Corrugated", diameters: "150–630 mm" },
    ],
    featured: true,
    color: "#22d3ee",
  },
  {
    id: "frutibest",
    name: "FrutiBest SHPK",
    country: "Albania",
    specialty: "Corrugated HDPE Pipe Systems",
    tagline: "Albanian supplier of corrugated drainage solutions",
    maxDiameter: "ID 2000 mm",
    description:
      "FrutiBest SHPK supplies corrugated HDPE pipe systems for drainage and sewage applications. Specializing in SN4 and SN8 corrugated pipes, as well as large-diameter KRAH pipe systems for municipal infrastructure projects.",
    website: "",
    partnerType: "local-albania",
    keyStandards: ["EN 13476-3", "ISO 9969"],
    heroMetrics: ["SN4 / SN8", "KRAH systems", "ID up to 2000 mm"],
    logo: {},
    featuredPriority: 15,
    products: [
      { name: "Corrugated HDPE SN4/SN8", type: "HDPE Corrugated", diameters: "110–1000 mm" },
      { name: "KRAH Pipe System", type: "HDPE KRAH", diameters: "800–2000 mm" },
    ],
    featured: false,
    color: "#10b981",
  },
  {
    id: "fitt",
    name: "FITT",
    country: "Italy",
    specialty: "Technical Hoses & Garden Systems",
    tagline: "Italian hose engineering for every application",
    maxDiameter: "Ø 100 mm",
    description:
      "FITT is a leading Italian manufacturer of thermoplastic hoses for garden, industrial, and water-supply applications. Key product lines include FITT Force, FITT Mint, and FITT Mimosa.",
    website: "https://fitt.com",
    partnerType: "hoses",
    keyStandards: ["EN ISO 1307", "REACH"],
    heroMetrics: ["3 flagship lines", "Global distribution", "Made in Italy"],
    logo: { dark: "/partners/fitt/logo.svg", light: "/partners/fitt/logo-light.svg" },
    featuredPriority: 4,
    products: [
      { name: "FITT Force", type: "Reinforced PVC Hose", diameters: "12–50 mm" },
      { name: "FITT Mint", type: "Garden Hose", diameters: "12–25 mm" },
      { name: "FITT Mimosa", type: "Lightweight Hose", diameters: "12–19 mm" },
    ],
    featured: true,
    color: "#06b6d4",
  },
  {
    id: "plastika-ks",
    name: "PLASTIKA",
    country: "Kosovo",
    specialty: "Recycling → Granulates → Agricultural & Construction Foils",
    tagline: "Circular-economy plastics for agriculture & construction",
    description:
      "PLASTIKA processes recycled plastics into granulates and produces agricultural and construction foils, contributing to the circular economy in the Balkans.",
    website: "https://plastika-ks.com/en",
    partnerType: "recycler",
    keyStandards: ["ISO 14001"],
    heroMetrics: ["Recycled granulates", "Agri & construction foils"],
    logo: { dark: "/partners/plastika-ks/logo.svg", light: "/partners/plastika-ks/logo-light.svg" },
    featuredPriority: 5,
    products: [
      { name: "Recycled Granulates", type: "HDPE/LDPE Granulate", diameters: "N/A" },
      { name: "Agricultural Film", type: "PE Film", diameters: "N/A" },
    ],
    featured: true,
    color: "#22c55e",
  },
  {
    id: "assos-viokon",
    name: "ASSOS-VIOKON",
    country: "Greece",
    specialty: "Plastic Food Packaging — Barrels & Accessories",
    tagline: "Greek packaging specialist for food & industry",
    description:
      "ASSOS-VIOKON manufactures plastic food-packaging items including general and specialty barrels plus related accessories for the food-service and industrial sectors.",
    website: "https://viokon.gr",
    partnerType: "packaging",
    keyStandards: ["EU Food Contact"],
    heroMetrics: ["Barrels & accessories", "Food-grade plastics"],
    logo: { dark: "/partners/assos-viokon/logo.svg", light: "/partners/assos-viokon/logo-light.svg" },
    featuredPriority: 8,
    products: [
      { name: "General Barrels", type: "Food-Grade Plastic", diameters: "N/A" },
      { name: "Special Barrels", type: "Food-Grade Plastic", diameters: "N/A" },
    ],
    featured: false,
    color: "#3b82f6",
  },
  {
    id: "polins",
    name: "Polins",
    country: "Serbia",
    specialty: "Manual Sprayers, Animal Troughs & Farm Plastics",
    tagline: "Serbian agricultural plastics specialist",
    description:
      "Polins is a Serbian manufacturer of plastic equipment for agriculture and animal husbandry — manual sprayer pumps from 1 to 16 L, milk and feed containers, poultry and livestock troughs, plant pots and plastic implements.",
    website: "https://polins.co.rs",
    partnerType: "manufacturer",
    keyStandards: [],
    heroMetrics: ["Sprayers 1–16 L", "Animal troughs", "Farm tools"],
    logo: { dark: "/partners/polins/logo.svg", light: "/partners/polins/logo-light.svg" },
    featuredPriority: 9,
    products: [
      { name: "Manual Sprayer Pumps", type: "Pressurised PE", diameters: "1 / 1.5 / 2 / 2.5 / 5 / 10 / 12 / 16 L" },
      { name: "Milk & Feed Containers", type: "Food-Grade PE", diameters: "10 / 15 / 20 L" },
      { name: "Poultry & Livestock Troughs", type: "PE", diameters: "200 / 250 / 340 / 400 / 445 mm" },
      { name: "Plant Pots & Plastic Tools", type: "PE", diameters: "Various" },
    ],
    featured: false,
    color: "#64748b",
  },
  {
    id: "plastika-nv",
    name: "Plastika DOO Nova Varoš",
    country: "Serbia",
    specialty: "Plastic Processing & Packaging with In-House Recycling",
    tagline: "Packaging factory with in-house recycling & solar initiative",
    description:
      "Plastika DOO Nova Varoš is a plastic-processing and packaging factory with in-house recycling capabilities and a solar-energy initiative for sustainable operations.",
    website: "https://plastikanv.com",
    partnerType: "recycler",
    keyStandards: [],
    heroMetrics: ["In-house recycling", "Solar-powered ops"],
    logo: { dark: "/partners/plastika-nv/logo.svg", light: "/partners/plastika-nv/logo-light.svg" },
    featuredPriority: 10,
    products: [
      { name: "Plastic Packaging", type: "PE/PP Packaging", diameters: "N/A" },
    ],
    featured: false,
    color: "#64748b",
  },
  {
    id: "poly-plast-system",
    name: "Poly Plast System",
    country: "Albania",
    specialty: "Plastic Pipe Manufacturer",
    tagline: "Albanian pipe manufacturer",
    description:
      "Poly Plast System is an Albanian manufacturer of plastic pipe systems for water supply and infrastructure projects.",
    website: "https://polyplastsystem.com",
    partnerType: "local-albania",
    keyStandards: [],
    heroMetrics: ["Local manufacturer"],
    logo: { dark: "/partners/poly-plast-system/logo.svg", light: "/partners/poly-plast-system/logo-light.svg" },
    featuredPriority: 7,
    products: [
      { name: "PE Pipe Systems", type: "HDPE", diameters: "20–400 mm" },
    ],
    featured: false,
    color: "#ef4444",
  },
  {
    id: "sel-polimer",
    name: "Polimer Kauçuk / SEL-Polimer",
    country: "Turkey",
    specialty: "Rubber & PVC Hose Manufacturer",
    tagline: "Turkish hose manufacturer since 1957",
    description:
      "Polimer Kauçuk Sanayi (SEL-Polimer) has been manufacturing rubber and PVC hoses since 1957, serving industrial, agricultural, and construction markets.",
    website: "https://sel-polimer.com",
    partnerType: "hoses",
    keyStandards: ["ISO 9001"],
    heroMetrics: ["Est. 1957", "Rubber & PVC hoses"],
    logo: { dark: "/partners/sel-polimer/logo.svg", light: "/partners/sel-polimer/logo-light.svg" },
    featuredPriority: 6,
    products: [
      { name: "Industrial Rubber Hose", type: "Rubber", diameters: "6–150 mm" },
      { name: "PVC Suction Hose", type: "PVC", diameters: "20–200 mm" },
    ],
    featured: false,
    color: "#f59e0b",
  },
  {
    id: "perplast",
    name: "Perplast Kompani",
    country: "North Macedonia",
    specialty: "PVC Hoses & PVC Granulate",
    tagline: "PVC hose & granulate producer from Tetovo",
    description:
      "Based in Tetovo, Perplast Kompani produces PVC hoses and PVC granulate for regional distribution.",
    website: "",
    partnerType: "hoses",
    keyStandards: [],
    heroMetrics: ["PVC hoses", "PVC granulate"],
    logo: { dark: "/partners/perplast/logo.svg", light: "/partners/perplast/logo-light.svg" },
    featuredPriority: 11,
    products: [
      { name: "PVC Hose", type: "PVC", diameters: "10–100 mm" },
      { name: "PVC Granulate", type: "PVC Granulate", diameters: "N/A" },
    ],
    featured: false,
    color: "#64748b",
  },
  {
    id: "albplast",
    name: "Albplast",
    country: "Albania",
    specialty: "Irrigation & Water Pipe Systems",
    tagline: "Albanian producer for irrigation & water networks",
    description:
      "Albplast is an Albanian producer focused on irrigation and water-pipe systems for local and regional infrastructure projects.",
    website: "",
    partnerType: "local-albania",
    keyStandards: [],
    heroMetrics: ["Irrigation focus"],
    logo: {},
    featuredPriority: 12,
    products: [
      { name: "Irrigation Pipe", type: "PE", diameters: "20–110 mm" },
    ],
    featured: false,
    color: "#64748b",
  },
  {
    id: "palaplast",
    name: "Palaplast",
    country: "Greece",
    specialty: "PE Pipes, Compression Fittings & Irrigation",
    tagline: "Greek manufacturer for irrigation systems",
    description:
      "Palaplast is a Greek manufacturer specialising in PE pipes, compression fittings and a complete range of irrigation accessories — filters, drip emitters, end caps and reed couplers — supplied across Greece and the wider Balkan region.",
    website: "https://www.palaplast.gr",
    partnerType: "manufacturer",
    keyStandards: [],
    heroMetrics: ["6 / 10 ATM PE", "Compression fittings", "Drip irrigation"],
    logo: {},
    featuredPriority: 13,
    products: [
      { name: "PE Pipes 6 / 10 ATM", type: "LDPE / HDPE", diameters: "Ø20–110 mm" },
      { name: "PE Compression Fittings", type: "PE", diameters: "Ø20–110 mm" },
      { name: "Irrigation Filters", type: "Disc / Mesh", diameters: "3/4″–2″" },
      { name: "Drip Emitters", type: "Inline / Online", diameters: "16 / 20 / 25 / 32 mm" },
      { name: "End Caps & Reed Couplers", type: "PE", diameters: "1/2″–4″" },
    ],
    featured: false,
    color: "#84cc16",
  },
  {
    id: "pista-ekoplast",
    name: "Pista Ekoplast",
    country: "Kosovo",
    specialty: "PVC Garden & Irrigation Hose",
    tagline: "Kosovo-based PVC hose producer",
    description:
      "Pista Ekoplast is a Kosovo-based producer specialised in flexible PVC hose for garden and irrigation use, supplied in standard ½″, ¾″, and 1″ sizes.",
    website: "",
    partnerType: "hoses",
    keyStandards: [],
    heroMetrics: ["½″–1″ sizes", "Single-line focus"],
    logo: {},
    featuredPriority: 14,
    products: [
      { name: "PVC Garden Hose", type: "PVC", diameters: "13 / 19 / 25 mm" },
    ],
    featured: false,
    color: "#ec4899",
  },
  {
    id: "roto",
    name: "Roto",
    country: "North Macedonia",
    specialty: "Decorative Plastic Planters & Garden Pots",
    tagline: "Designer planters and outdoor pottery",
    description:
      "Roto produces a wide catalogue of injection-moulded decorative planters, vases and garden pots in styles including Edelweis, Stoniness, Teak, Modern, Samba, Balcone, Tulip and Barrel — supplied in S/M/L/XL sizes for residential, hospitality and commercial landscaping.",
    website: "https://roto.mk",
    partnerType: "manufacturer",
    keyStandards: [],
    heroMetrics: ["Decorative pots", "Multiple styles", "S–XXL sizes"],
    logo: {},
    featuredPriority: 15,
    products: [
      { name: "Decorative Garden Planters", type: "Injection-moulded PE", diameters: "S / M / L / XL / XXL" },
      { name: "Wall-Mounted Pots", type: "Injection-moulded PE", diameters: "Single size" },
      { name: "Watering Cans", type: "Injection-moulded PE", diameters: "Standard" },
    ],
    featured: false,
    color: "#14b8a6",
  },
  {
    id: "confort-al",
    name: "Confort",
    country: "Albania",
    specialty: "PVC Fittings Catalogue",
    tagline: "Full PVC fittings range",
    description:
      "Confort supplies a comprehensive catalogue of PVC fittings — sockets, elbows, tees, reducers and adaptors — covering common diameters used across plumbing and drainage installations in Albania.",
    website: "https://confort-al.com",
    partnerType: "local-albania",
    keyStandards: [],
    heroMetrics: ["PVC fittings", "Full range"],
    logo: {},
    featuredPriority: 16,
    products: [
      { name: "PVC Fittings", type: "PVC", diameters: "Various" },
    ],
    featured: false,
    color: "#6366f1",
  },
  {
    id: "xier-valve",
    name: "Xier Valve",
    country: "China",
    specialty: "UPVC Industrial Ball Valves",
    tagline: "Industrial UPVC valve manufacturer",
    description:
      "Xier Valve manufactures UPVC compact ball valves for water supply, irrigation and chemical-handling applications, supplied in standard threaded sizes.",
    website: "https://www.xiervalve.com",
    partnerType: "manufacturer",
    keyStandards: [],
    heroMetrics: ["UPVC valves", "Compact design"],
    logo: {},
    featuredPriority: 17,
    products: [
      { name: "UPVC Compact Ball Valve", type: "UPVC", diameters: "Threaded sizes" },
    ],
    featured: false,
    color: "#f97316",
  },
];

export const partnerTypeLabels: Record<PartnerType, string> = {
  manufacturer: "Manufacturers",
  recycler: "Recycling & Foils",
  packaging: "Packaging",
  hoses: "Hoses",
  "local-albania": "Local Albania",
};

export const timeline = [
  {
    year: 1995,
    title: "Foundation",
    description:
      "Sukaj SHPK established in the Shkodër area as a specialized trading company focused on import-export of plastic materials.",
    milestone: "company_founded",
  },
  {
    year: 2009,
    title: "Capital Restructuring",
    description:
      "Major capital restructuring reaching 74,482,766 ALL. Expanding wholesale partnerships across Southeast Europe.",
    milestone: "capital_growth",
  },
  {
    year: 2015,
    title: "European Expansion",
    description:
      "Formal partnerships with Konti Hidroplast and FITT. Becoming a premier pipe-system distributor for the Balkans.",
    milestone: "partnerships",
  },
  {
    year: 2024,
    title: "Regional Network",
    description:
      "Consolidated a network of 12 partner manufacturers across 7 countries — Albania, Kosovo, North Macedonia, Serbia, Greece, Italy, and Turkey.",
    milestone: "network_growth",
    highlight: true,
  },
];

export const locations = [
  {
    id: "vore-tirana",
    name: "Vorë, Tirana",
    label: "Warehouse & Distribution",
    address: "Rruga Dytësore, Vorë, Tiranë 1001",
    description: "Central distribution hub on the Tiranë–Vorë highway, serving the capital region and southern Albania.",
    coordinates: { lat: 41.3748627, lng: 19.6773701 },
    mapUrl: "https://maps.app.goo.gl/4sfk7zTCD12MdgHj7?g_st=aw",
    mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2994.5!2d19.6517!3d41.3928!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDIzJzM0LjEiTiAxOcKwMzknMDYuMSJF!5e0!3m2!1sen!2s!4v1",
  },
  {
    id: "shkoder",
    name: "Shkodër",
    label: "Headquarters",
    address: "Shkodër, Albania",
    description: "Company headquarters and primary operations center since 1995. Main office and showroom.",
    coordinates: { lat: 42.1188879, lng: 19.4960235 },
    mapUrl: "https://maps.app.goo.gl/YTsRT62aPVW9BXnb6",
    mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2960.5!2d19.5033!3d42.0693!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDLCsDA0JzA5LjUiTiAxOcKwMzAnMTEuOSJF!5e0!3m2!1sen!2s!4v1",
  },
  {
    id: "lac",
    name: "Laç",
    label: "Regional Depot",
    address: "Laç, Kurbin, Albania",
    description: "Northern regional storage and fast-delivery depot for Kurbin and surrounding districts.",
    coordinates: { lat: 41.6035026, lng: 19.6686082 },
    mapUrl: "https://maps.app.goo.gl/14Q7Hq7PxrW2xstx8",
    mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2982.5!2d19.7131!3d41.6358!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDM4JzA4LjkiTiAxOcKwNDInNDcuMiJF!5e0!3m2!1sen!2s!4v1",
  },
];

export const categories = [
  {
    id: "civil",
    name: "Civil Engineering",
    description: "Municipal infrastructure, sewage systems, and urban drainage solutions.",
    icon: "Building2",
    products: ["Spiral Sewage Pipe", "Corrugated HDPE SN4", "Corrugated Sewage Pipe"],
  },
  {
    id: "agri",
    name: "Agriculture",
    description: "Irrigation systems, water management, and agricultural drainage.",
    icon: "Sprout",
    products: ["FITT Force", "FITT Mint", "Irrigation Pipe", "Agricultural Film"],
  },
  {
    id: "industrial",
    name: "Industrial",
    description: "Heavy-duty conduits, cable protection, and factory infrastructure.",
    icon: "Factory",
    products: [
      "Industrial Rubber Hose",
      "PVC Suction Hose",
      "Solid Wall PE Pipe",
    ],
  },
];

export interface Product {
  id: number;
  slug: string;
  name: string;
  partner: string;
  partnerId: string;
  category: string;
  material: string;
  application: string;
  diameterMin: number;
  diameterMax: number;
  description: string;
  standard?: string[];
  pressureClass?: string;
  datasheetUrl?: string;
  image?: string;
  specs: Record<string, string>;
}

export const products: Product[] = [
  {
    id: 1,
    slug: "konti-spiral-sewage",
    name: "Spiral Sewage Pipe",
    partner: "Konti Hidroplast",
    partnerId: "konti-hidroplast",
    category: "civil",
    material: "PP",
    application: "Sewage",
    diameterMin: 300,
    diameterMax: 2000,
    description:
      "Spiral-wound polypropylene sewage pipe for municipal and industrial waste-water networks. Available in large diameters for trunk-line applications.",
    standard: ["EN 13476"],
    pressureClass: "SN4–SN16",
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&h=600&fit=crop&q=80",
    specs: {
      wallType: "Spiral-wound structured wall",
      length: "6 m standard",
      joints: "Integrated rubber seal",
    },
  },
  {
    id: 2,
    slug: "konti-solid-wall-pe",
    name: "Solid Wall PE Pipe",
    partner: "Konti Hidroplast",
    partnerId: "konti-hidroplast",
    category: "civil",
    material: "HDPE",
    application: "Water",
    diameterMin: 20,
    diameterMax: 630,
    description:
      "PE100 solid-wall pressure pipe for potable water and gas networks.",
    standard: ["EN 12201"],
    pressureClass: "PN6–PN25",
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&h=600&fit=crop&q=80",
    specs: {
      material: "PE100",
      color: "Black with blue stripe",
      coilsOrBars: "Coils ≤110 mm / Bars 6–12 m",
    },
  },
  {
    id: 3,
    slug: "ferplast-corrugated-sn4",
    name: "Corrugated HDPE SN4",
    partner: "Ferplast",
    partnerId: "ferplast-ks",
    category: "civil",
    material: "HDPE",
    application: "Sewage",
    diameterMin: 100,
    diameterMax: 2000,
    description:
      "Double-wall corrugated HDPE pipe at SN4 stiffness class for gravity sewage and storm-water drainage.",
    standard: ["EN 13476", "SN4"],
    pressureClass: "SN4",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&q=80",
    specs: {
      structure: "Smooth inner / corrugated outer",
      joints: "Coupler with rubber seal",
      length: "6 m",
    },
  },
  {
    id: 4,
    slug: "ferplast-corrugated-sn8",
    name: "Corrugated HDPE SN8",
    partner: "Ferplast",
    partnerId: "ferplast-ks",
    category: "civil",
    material: "HDPE",
    application: "Drainage",
    diameterMin: 100,
    diameterMax: 1200,
    description:
      "Higher-stiffness corrugated HDPE pipe for deeper burial depths and heavier traffic loads.",
    standard: ["EN 13476", "SN8"],
    pressureClass: "SN8",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop&q=80",
    specs: {
      structure: "Smooth inner / corrugated outer",
      joints: "Coupler with rubber seal",
      length: "6 m",
    },
  },
  {
    id: 5,
    slug: "teqja-hdpe100",
    name: "HDPE 100 Pressure Pipe",
    partner: "Teqja International",
    partnerId: "teqja",
    category: "civil",
    material: "HDPE",
    application: "Water",
    diameterMin: 20,
    diameterMax: 630,
    description:
      "Locally manufactured HDPE PE100 pressure pipe, PN4–PN32, for water supply and irrigation mains.",
    standard: ["EN 12201", "ISO 9001"],
    pressureClass: "PN4–PN32",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&h=600&fit=crop&q=80",
    specs: {
      material: "PE100",
      lengths: "6 m / 12 m bars; coils ≤110 mm",
      color: "Black with blue stripe",
    },
  },
  {
    id: 6,
    slug: "teqja-corrugated-sewage",
    name: "Corrugated Sewage Pipe",
    partner: "Teqja International",
    partnerId: "teqja",
    category: "civil",
    material: "HDPE",
    application: "Sewage",
    diameterMin: 150,
    diameterMax: 630,
    description:
      "EN 13476-1:2018 corrugated sewage pipe produced in 12 m lengths for municipal networks.",
    standard: ["EN 13476-1:2018"],
    image: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&h=600&fit=crop&q=80",
    specs: {
      structure: "Double-wall corrugated",
      length: "12 m",
      joints: "Rubber-seal coupler",
    },
  },
  {
    id: 7,
    slug: "fitt-force",
    name: "FITT Force",
    partner: "FITT",
    partnerId: "fitt",
    category: "agri",
    material: "PVC",
    application: "Water",
    diameterMin: 12,
    diameterMax: 50,
    description:
      "Reinforced PVC hose designed for demanding garden and light irrigation use. High burst-pressure resistance.",
    standard: ["EN ISO 1307"],
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop&q=80",
    specs: {
      reinforcement: "Textile braid",
      maxPressure: "30 bar burst",
      temperature: "-10 °C to +60 °C",
    },
  },
  {
    id: 8,
    slug: "fitt-mint",
    name: "FITT Mint",
    partner: "FITT",
    partnerId: "fitt",
    category: "agri",
    material: "PVC",
    application: "Water",
    diameterMin: 12,
    diameterMax: 25,
    description:
      "Mid-range garden hose with anti-twist technology and NTS® system for easy connection.",
    image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&h=600&fit=crop&q=80",
    specs: {
      feature: "Anti-twist NTS® system",
      length: "15–50 m",
      color: "Mint green",
    },
  },
  {
    id: 9,
    slug: "fitt-mimosa",
    name: "FITT Mimosa",
    partner: "FITT",
    partnerId: "fitt",
    category: "agri",
    material: "PVC",
    application: "Water",
    diameterMin: 12,
    diameterMax: 19,
    description:
      "Ultra-lightweight, compact garden hose that expands under pressure. Ideal for small gardens and balconies.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&q=80",
    specs: {
      feature: "Auto-expanding",
      weight: "Ultra-light",
      length: "10–30 m",
    },
  },
  {
    id: 10,
    slug: "plastika-recycled-granulates",
    name: "Recycled Granulates",
    partner: "PLASTIKA",
    partnerId: "plastika-ks",
    category: "industrial",
    material: "HDPE",
    application: "Recycling",
    diameterMin: 0,
    diameterMax: 0,
    description:
      "Recycled HDPE and LDPE granulates produced from post-industrial and post-consumer waste. Base material for film and pipe extrusion.",
    standard: ["ISO 14001"],
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&h=600&fit=crop&q=80",
    specs: {
      inputStream: "Post-industrial / post-consumer",
      outputForm: "Pelletised granulate",
      applications: "Film, pipe, injection",
    },
  },
  {
    id: 11,
    slug: "plastika-agri-film",
    name: "Agricultural Film",
    partner: "PLASTIKA",
    partnerId: "plastika-ks",
    category: "agri",
    material: "LDPE",
    application: "Agriculture",
    diameterMin: 0,
    diameterMax: 0,
    description:
      "PE film for greenhouse covering, mulching, and silage — produced from recycled granulates.",
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&h=600&fit=crop&q=80",
    specs: {
      thickness: "40–200 µm",
      width: "Up to 12 m",
      uvStabilised: "Yes",
    },
  },
  {
    id: 12,
    slug: "sel-polimer-rubber-hose",
    name: "Industrial Rubber Hose",
    partner: "Polimer Kauçuk / SEL-Polimer",
    partnerId: "sel-polimer",
    category: "industrial",
    material: "Rubber",
    application: "Industrial",
    diameterMin: 6,
    diameterMax: 150,
    description:
      "Heavy-duty rubber hoses for air, water, oil, and chemical transfer in industrial environments.",
    standard: ["ISO 9001"],
    image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&h=600&fit=crop&q=80",
    specs: {
      reinforcement: "Textile / wire braid",
      temperature: "-30 °C to +100 °C",
      pressure: "10–40 bar WP",
    },
  },
  {
    id: 13,
    slug: "sel-polimer-pvc-suction",
    name: "PVC Suction Hose",
    partner: "Polimer Kauçuk / SEL-Polimer",
    partnerId: "sel-polimer",
    category: "industrial",
    material: "PVC",
    application: "Water",
    diameterMin: 20,
    diameterMax: 200,
    description:
      "PVC suction and delivery hose with rigid PVC helix for water, slurry, and light-chemical transfer.",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop&q=80",
    specs: {
      helix: "Rigid PVC spiral",
      vacuum: "Up to −0.9 bar",
      temperature: "-10 °C to +60 °C",
    },
  },
  {
    id: 14,
    slug: "poly-plast-pe-water-pipe",
    name: "PE Water Supply Pipe",
    partner: "Poly Plast System",
    partnerId: "poly-plast-system",
    category: "civil",
    material: "HDPE",
    application: "Water",
    diameterMin: 20,
    diameterMax: 400,
    description:
      "PE80/PE100 water supply pipe for potable water distribution networks. Produced locally in Albania for fast regional delivery.",
    standard: ["EN 12201", "ISO 4427"],
    pressureClass: "PN6–PN16",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&q=80",
    specs: {
      material: "PE80 / PE100",
      color: "Black or blue",
      lengths: "Coils ≤63 mm / Bars 6–12 m",
    },
  },
  {
    id: 15,
    slug: "albplast-irrigation-drip",
    name: "Drip Irrigation Pipe",
    partner: "Albplast",
    partnerId: "albplast",
    category: "agri",
    material: "LDPE",
    application: "Agriculture",
    diameterMin: 16,
    diameterMax: 32,
    description:
      "Thin-wall LDPE drip irrigation lateral pipe with integrated or insertable emitters for row crops, vineyards, and orchards.",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop&q=80",
    specs: {
      wallThickness: "0.9–1.5 mm",
      emitterSpacing: "20 / 30 / 50 cm",
      rollLength: "200 / 500 m",
    },
  },
  {
    id: 16,
    slug: "albplast-pe-irrigation-main",
    name: "PE Irrigation Mainline",
    partner: "Albplast",
    partnerId: "albplast",
    category: "agri",
    material: "HDPE",
    application: "Agriculture",
    diameterMin: 20,
    diameterMax: 110,
    description:
      "PE100 mainline pipe for pressurised irrigation systems — compatible with standard fittings for sprinkler and drip networks.",
    standard: ["ISO 4427"],
    pressureClass: "PN10–PN16",
    image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&h=600&fit=crop&q=80",
    specs: {
      color: "Black",
      coilLength: "Up to 200 m",
      jointing: "Butt fusion / electrofusion",
    },
  },
  {
    id: 17,
    slug: "polins-agricultural-film",
    name: "Greenhouse Cover Film",
    partner: "Polins doo",
    partnerId: "polins",
    category: "agri",
    material: "LDPE",
    application: "Agriculture",
    diameterMin: 0,
    diameterMax: 0,
    description:
      "UV-stabilised LDPE greenhouse cover and mulch film for season extension and soil management in intensive agriculture.",
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&h=600&fit=crop&q=80",
    specs: {
      thickness: "80–200 µm",
      width: "4–14 m",
      uvLifetime: "2–5 years",
    },
  },
  {
    id: 18,
    slug: "perplast-pvc-hose",
    name: "PVC Garden Hose",
    partner: "Perplast Kompani",
    partnerId: "perplast",
    category: "agri",
    material: "PVC",
    application: "Water",
    diameterMin: 10,
    diameterMax: 50,
    description:
      "Flexible PVC garden and light-irrigation hose. Reinforced with textile yarn for improved burst pressure and kink resistance.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&q=80",
    specs: {
      reinforcement: "Textile yarn braid",
      maxPressure: "8 bar WP",
      temperature: "-5 °C to +50 °C",
    },
  },
  {
    id: 19,
    slug: "plastika-nv-packaging",
    name: "Industrial PE Packaging Film",
    partner: "Plastika DOO Nova Varoš",
    partnerId: "plastika-nv",
    category: "industrial",
    material: "LDPE",
    application: "Industrial",
    diameterMin: 0,
    diameterMax: 0,
    description:
      "Stretch and shrink PE films for pallet wrapping, product bundling, and protective industrial packaging.",
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&h=600&fit=crop&q=80",
    specs: {
      thickness: "15–50 µm",
      width: "Up to 2 000 mm",
      coreSize: "76 mm",
    },
  },
  {
    id: 20,
    slug: "assos-viokon-food-barrel",
    name: "Food-Grade Plastic Barrel",
    partner: "ASSOS-VIOKON",
    partnerId: "assos-viokon",
    category: "industrial",
    material: "HDPE",
    application: "Industrial",
    diameterMin: 0,
    diameterMax: 0,
    description:
      "EU food-contact certified HDPE barrels for storage and transport of liquids, semi-liquids, and solid foodstuffs.",
    standard: ["EU 10/2011"],
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&h=600&fit=crop&q=80",
    specs: {
      capacity: "30 / 60 / 120 / 220 L",
      closure: "Screw-top lid",
      stackable: "Yes",
    },
  },
  {
    id: 21,
    slug: "konti-pe-gas-pipe",
    name: "PE Gas Distribution Pipe",
    partner: "Konti Hidroplast",
    partnerId: "konti-hidroplast",
    category: "civil",
    material: "HDPE",
    application: "Gas",
    diameterMin: 20,
    diameterMax: 315,
    description:
      "PE100-RC gas distribution pipe with yellow stripe for natural gas and LPG networks, meeting EN 1555 standard.",
    standard: ["EN 1555", "EN 12201"],
    pressureClass: "PN4–PN10",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&h=600&fit=crop&q=80",
    specs: {
      material: "PE100-RC",
      color: "Black with yellow stripe",
      SDR: "SDR 11 / SDR 17",
    },
  },
  {
    id: 22,
    slug: "sel-polimer-air-hose",
    name: "Compressed Air Hose",
    partner: "Polimer Kauçuk / SEL-Polimer",
    partnerId: "sel-polimer",
    category: "industrial",
    material: "Rubber",
    application: "Industrial",
    diameterMin: 6,
    diameterMax: 50,
    description:
      "Rubber compressed air hose with textile reinforcement for pneumatic tools, compressors, and workshop applications.",
    standard: ["ISO 9001"],
    image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&h=600&fit=crop&q=80",
    specs: {
      reinforcement: "Two textile braid plies",
      maxPressure: "20 bar WP",
      temperature: "-25 °C to +80 °C",
    },
  },
  {
    id: 23,
    slug: "ferplast-inspection-chamber",
    name: "HDPE Inspection Chamber",
    partner: "Ferplast",
    partnerId: "ferplast-ks",
    category: "civil",
    material: "HDPE",
    application: "Sewage",
    diameterMin: 315,
    diameterMax: 630,
    description:
      "Prefabricated HDPE inspection chamber for gravity sewage and stormwater networks — reduces site installation time.",
    standard: ["EN 13598"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&q=80",
    specs: {
      bodyDiameter: "315 / 425 / 630 mm",
      depth: "Up to 6 m",
      cover: "Load class B125–D400",
    },
  },
  {
    id: 24,
    slug: "plastika-ks-construction-film",
    name: "Construction Damp-Proof Membrane",
    partner: "PLASTIKA",
    partnerId: "plastika-ks",
    category: "civil",
    material: "LDPE",
    application: "Construction",
    diameterMin: 0,
    diameterMax: 0,
    description:
      "Heavy-duty PE damp-proof membrane for under-slab and foundation waterproofing, produced from recycled PE granulates.",
    image: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&h=600&fit=crop&q=80",
    specs: {
      thickness: "200–500 µm",
      width: "2–8 m",
      standard: "EN 13967",
    },
  },
];
